name: FoxetGSI-builder

on:
  workflow_dispatch:
    inputs:
      rom_type:
        description: 'Type of ROM (e.g., Pixel, Generic)'
        required: true
        default: 'Pixel'
      rom_link:
        description: 'Link to the ROM file'
        required: true
        default: 'https://dl.google.com/dl/android/aosp/barbet-sp1a.210812.015-factory-13f4d9f2.zip'
      rom_type_option:
        description: 'Type of GSI (AB or A-only)'
        required: true
        default: 'AB'

jobs:
  Build_GSI:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone AndroDumb/FoxetGSITool
        run: |
          git clone --recurse-submodules https://github.com/AndroDumb/FoxetGSITool.git

      - name: Install dependencies
        run: |
          cd FoxetGSITool
          sudo bash FoxetGSITool.sh
          sudo apt-get install -y p7zip-full

      - name: Build GSI
        env:
          ROM_TYPE: ${{ github.event.inputs.rom_type }}
          ROM_LINK: ${{ github.event.inputs.rom_link }}
          ROM_TYPE_OPTION: ${{ github.event.inputs.rom_type_option }}
        run: |
          cd FoxetGSITool
          if [ "$ROM_TYPE_OPTION" = "AB" ]; then
            sudo bash LinkToGSI.sh "$ROM_LINK" "$ROM_TYPE" --ab
          else
            sudo bash LinkToGSI.sh "$ROM_LINK" "$ROM_TYPE" --aonly
          fi

      - name: Prepare artifacts directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts
          sudo chmod -R 777 $GITHUB_WORKSPACE/artifacts

      - name: Move images to output directory (compatibilidad Output/output)
        run: |
          mkdir -p $GITHUB_WORKSPACE/FoxetGSITool/output
          if [ -d "$GITHUB_WORKSPACE/FoxetGSITool/Output" ]; then
            cp $GITHUB_WORKSPACE/FoxetGSITool/Output/*.img $GITHUB_WORKSPACE/FoxetGSITool/output/ 2>/dev/null || true
            cp $GITHUB_WORKSPACE/FoxetGSITool/Output/*.txt $GITHUB_WORKSPACE/FoxetGSITool/output/ 2>/dev/null || true
          fi

      - name: Process and Package Files
        id: package
        run: |
          cd $GITHUB_WORKSPACE/FoxetGSITool/output || exit 1
          if [ $(ls -1 *.img 2>/dev/null | wc -l) -eq 0 ]; then
            echo "::error::No .img files found!"
            exit 1
          fi
          timestamp=$(date +'%d.%m.%y_%H.%M')
          for img_file in *.img; do
            base_name="${img_file%.img}"
            txt_file="${base_name}.txt"
            # Si existe el .txt, lo copiamos, si no, igual seguimos
            if [ -f "$txt_file" ]; then
              cp "$txt_file" "$GITHUB_WORKSPACE/artifacts/"
              echo "txt_file=${txt_file}" >> $GITHUB_OUTPUT
            else
              echo "::warning::No ${txt_file} found for ${img_file}"
              echo "txt_file=" >> $GITHUB_OUTPUT
            fi
            7z a -mmt=on "$GITHUB_WORKSPACE/artifacts/${base_name}.7z" "$img_file"
            echo "release_name=${base_name}_${timestamp}" >> $GITHUB_OUTPUT
            echo "tag_name=${base_name}-${timestamp}" >> $GITHUB_OUTPUT
            echo "file_name=${base_name}.7z" >> $GITHUB_OUTPUT
          done

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package.outputs.tag_name }}
          name: ${{ steps.package.outputs.release_name }}
          body_path: ${{ steps.package.outputs.txt_file && format('artifacts/{0}', steps.package.outputs.txt_file) || '' }}
          files: |
            ${{ github.workspace }}/artifacts/${{ steps.package.outputs.file_name }}
            ${{ github.workspace }}/artifacts/${{ steps.package.outputs.txt_file }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
